### ISSUE TITLE
New URL for https://datelazi.ro/latestData.json ?

### ISSUE THREAD

**Issue by cristianangyal** [mhlnu/covidro_frontend#1]
Is there another working URL replacing https://datelazi.ro/latestData.json?
Thank you.

**Comment by mhlnu** [comment]
Try https://d35p9e4fm9h3wo.cloudfront.net/latestData.json although the other one should also work. I'm using the one you want to replace and it works just fine. Then again, I also use the graphs.ro API.

**Comment by cristianangyal** [comment]
Thank you! The new link is working fi e. I'm using it for a Power BI report.
